### PR TITLE
Incorporating multiprocessing into time consuming functions. 

### PR DESCRIPTION
**Pull request by SrikanthKom**
The functions updated are: 
 - `cube_fix_badpix_isolated`
 - `cube_fix_badpix_clump`
 - `cube_correct_nan`

### CODE REVIEW

**Review by VChristiaens — APPROVED** [review]
This is an amazing job @SrikanthKom - thanks a lot for implementing and benchmarking all these improvements!

**Comment by VChristiaens** [comment]
@SrikanthKom the new changes did not pass the battery of automated tests for Python3.7 (see details in the corresponding test outputs), with the following importation error:
`ImportError: cannot import name 'shared_memory' from 'multiprocessing' (/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/multiprocessing/__init__.py)`
Do you see any easy fix to also keep the compatibility with Python3.7?

**Comment by SrikanthKom** [comment]
> @SrikanthKom the new changes did not pass the battery of automated tests for Python3.7 (see details in the corresponding test outputs), with the following importation error:
> `ImportError: cannot import name 'shared_memory' from 'multiprocessing' (/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/multiprocessing/__init__.py)`
> Do you see any easy fix to also keep the compatibility with Python3.7?

Hi Valentin, shared_memory was back ported to python 3.7. (https://pypi.org/project/shared-memory38/). Adding this as a dependency and  changing 'from multiprocessing import shared_memeory' (in badpixelremoval.py and cosmetics.py) to 'try:from multiprocessing import shared_memeory except: import shared_memory' should ideally fix the problem. Do you want me to make these changes from my end?

**Comment by VChristiaens** [comment]
Hi @SrikanthKom, the fix you propose sounds good. Yes please, could you include it in the pull request? Thanks!

**Comment by SrikanthKom** [comment]
Hi @VChristiaens , I have resolved the issue for shared_memory in python 3.7 as discussed above. Cheers.

**Pull request merged**
