### PR TITLE
Adding modification of the test function 

### PR DESCRIPTION
**Pull request by kanti92**
Hi Valentin. I have modified the test function, so now it works with both even and odds sizes.

### CODE REVIEW

**Comment by kanti92** [comment]
Solving error on test function

**Comment by kanti92** [comment]
I saw the error. I modified the get_circle function. Now it also has the option to return indices

**Comment by kanti92** [comment]
Now, I have modified the truth_even matrix. It was wrong.

**Comment by VChristiaens** [comment]
Thanks @kanti92 !

**Pull request merged**
