### PR TITLE
TST: tests for var/shapes.py (2)

### PR DESCRIPTION
**Pull request by r4lv**
- Refactoring of `shapes.py`, so the functions have a common API
- Tests.

### CODE REVIEW

**Comment by r4lv** [comment]
There are a few changes to the signature of some functions. I updated the other functions inside VIP as well, but please check if you use them somewhere!

Changed signatures:

- `get_ellipse`
- `get_annulus_segments`
- `get_ell_annulus`
- `get_circle`

Please check the commits marked with `API:` for details.

**Comment by r4lv** [comment]
Ready to be merged 😉

**Comment by carlgogo** [comment]
You've changed the signature of ``get_annulus_segments``? That function is used very often in VIP. Could you elaborate on the changes?

**Comment by r4lv** [comment]
In this PR I only changed the *return type* of `get_annulus_segments`. See the commit message:

> get_annulus_segments with mode="val" returned a ndarray with `nsegm` entries. It now returns a list instead, to match the other two modes.

The *signature* of `get_annulus_segments` was changed in https://github.com/vortex-exoplanet/VIP/pull/281, which was the "first part" of my work on `shapes.py`, which you already merged. There, I replaced the `output_values` parameter with `mode`. ([corresponding lines in the other PR](https://github.com/vortex-exoplanet/VIP/pull/281/files#diff-ea6654e8fbb106ef1d599e124bd134f5L389))

**Comment by carlgogo** [comment]
It's ok as long as the change doesn't affect the logic or break other functions in VIP. That seems to be the case. 

Regarding the new helping function ``_image_or_shape``, it should better be moved to ``conf.conf_utils`` which contains ``check_array``.

**Comment by r4lv** [comment]
I verified the other functions to make sure nothing breaks. The functions which call `get_annulus_segments` with `mode="value"` always work with one single annulus only and call `get_annulus_segments(...)[0]`, so nothing should change there.

**Pull request merged**
