### PR TITLE
Vip_VC pull request

### PR DESCRIPTION
**Pull request by VChristiaens**
Hola Carlos,

I could not find out how to make a pull request specific to only one or 2 files, like the ones we already reviewed by skype.
However, I have the impression that in any case a global pull request is going to be much easier to compare directly and discuss by skype the changes between the 2 vip versions.
Most of the changes are explained in the latest version of the pdf sent by email: List of all changes to VIP-VC_v3.pdf. In that document, texts in italic font corresponds to points already discussed by skype.

If any modification in the code, as shown in the pull request comparison, is not described in the document, it means it is either minor and/or consists in the deletion of blanks so that the whole code complies strictly with the standard coding style of 80 characters per line.

Now the question is when do we both have time to discuss it?
I guess it is going to be easier after the vortex yearly meeting, so what about Monday 7th?

Cheers,
Valentin

### CODE REVIEW

**Comment by carlgogo** [comment]
Hi Valentin, thanks for the pull request. The problem with this is that it will take more time to test everything (we should use automatized testing in the future). Monday 7th sounds good, could you please share cubes/frames to test each function? It will be better to have it in a notebook. Is it too late to show this IFS PCA during the vortex meeting (demo of VIP is thursday 2pm)?

**Comment by VChristiaens** [comment]
Hola Carlos,

I'm not sure what you mean by automatizing the testing.
I am preparing a dropbox folder with sub-folders containing cubes to test each of the new functions, so you won't have to implement a whole coherent script. I'll send you the dropbox link when I'm ready.

I am a bit too collapsed to prepare a notebook showing how to use the IFS PCA for Thursday though.
However, it is very similar to what you already have implemented for ADI PCA, I didn't change much the arguments, it just assumes input cubes that are ifs cubes instead of ADI cubes, and an input list consisting of scaling factors instead of parallactic angles. A basic way to compute the scaling factors consists in taking the ratio of the reference wavelength (typically the longest present in the ifs cube) with the wavelength of each channel. A more precise way to determine them can be done following the development presented in the Pueyo et al. 2015 paper.

Saludos,
Valentin



Date: Tue, 1 Sep 2015 06:55:08 -0700

**Comment by carlgogo** [comment]
With automatised testing I mean something along these lines:
https://pytest.org/latest/goodpractises.html <https://pytest.org/latest/goodpractises.html>
http://pythontesting.net <http://pythontesting.net/>

Maybe I could show the PCA for IFS data if I have the cubes. Let me know please.

Saludos,
Carlos

**Comment by carlgogo** [comment]
Salut Valentin, 

I hope you're doing fine and everything is alright in Chile. Right now I'm taking a look at the pull request. First thing, your branch is not up to date with the master. As you probably can see above "this branch has conflicts that must be resolved". Github shows how to update your branch to have the latest version of the master. Then you should resolve the conflicts of your changes with the current version of VIP. I already noticed the first: your function PCA() for full-frame PCA, is missing a parameter, which is another cube (reference star). This could be covered with your parameter "variation" (which must be renamed to "mode" to comply with the rest of functions) including an option for RDI. What I will do now is: 
- I will write my comments directly on the pull request, on the corresponding lines of your code (I just spotted that functionality)
- I will see if I can commit to your branch so I can help making the changes to the pull request in order to merge it asap.

Saludos,
Carlos

**Pull request closed without merging**
